### ISSUE TITLE
NPC collision

### ISSUE THREAD

**Issue by Coffee4cr** [miicck/dont-get-lost#10]
NPC's don't collide with each other, but collides with the player. I don't know if there's a reason for it, but removing the collision with the player would remove tons of annoyance of getting pushed around.

**Comment by Coffee4cr** [comment]
I've been looking at the code, and maybe It's just the trader that's colliding? I do know there was something pushing me around when trying to build my walls.

**Comment by Coffee4cr** [comment]
Tested it again tonight, NPCs in general body block you (but not themselves)

**Comment by miicck** [comment]
Duplicate of: https://github.com/miicck/dont-get-lost/issues/24
Which has been fixed.
