### ISSUE TITLE
Quest/Tutorial in Multiplayer

### ISSUE THREAD

**Issue by Coffee4cr** [miicck/dont-get-lost#11]
We either need a way to skip some of those tutorials, or make it so that in multiplayer, completing for one person completes them for all.

**Comment by Myystical** [comment]
I believe a temporary solution to this is to just give the item that the tutorial wants to your friend. It worked one time when my friend picked up the notice board that I placed down.

**Comment by Coffee4cr** [comment]
yeah, that's the way to "bypass" it for now

**Comment by miicck** [comment]
I've added an option to generate a world with no tutorial at all: a3c48367d715446df8fc50770001d0b1c8513fbb
So I'm marking this as fixed. If this misses something, please feel free to open a new issue :)
