### ISSUE TITLE
No easy way to delete items

### ISSUE THREAD

**Issue by TacoShower** [miicck/dont-get-lost#16]
Currently the only way to get rid of an item is to sell it to a merchant or to use a console command such as "give -1 bed" to remove 1 bed from inventory. This is not user friendly and leads to constantly having a full inventory. I suggest either a hotkey to delete with a prompt that comes up asking if they are sure, or a dedicated inventory slot that items can be dragged in to to delete.

**Comment by tlivesay** [comment]
Another easy way to get rid of items is to put them in a buffer chest that dumps to a dead end channel.

**Comment by miicck** [comment]
Fixed by: 0acf6739e12231476c95194b9503f1fcb69c7bc6
