### ISSUE TITLE
Trader items not showing proper image

### ISSUE THREAD

**Issue by Coffee4cr** [miicck/dont-get-lost#17]
Some images in the trader list do not correspond to the text with them.

he had the image of a titanium axe with the text iron axe, and it sold my titanium axe (was thinking it would get rid of my iron axe).
I've noticed a couple more, but I can't remember them off the top of my head

**Comment by miicck** [comment]
Fixed by ac4f9017f5affd308ad2271db9f1cca7055731db
Thanks @TacoShower !
