### ISSUE TITLE
Game locks up when clicking on noticeboard

### ISSUE THREAD

**Issue by swiftimundo** [miicck/dont-get-lost#18]
About 1/3 of the times I click on the noticeboard my controls lock up. Noticeboard screen never appears. I am unable to do anything, cant esc, or move. I can see the villagers moving around in the background though and day night cycle keeps going. Have to alt-f4 and lose all progress made since the last save.

**Comment by TacoShower** [comment]
@swiftimundo I haven't been able to replicate this myself, do you notice anything specific that happens beforehand? does it freeze up when holding a specific item or are there no villagers alive? I will keep testing to see if I can find what is causing it in the meantime

**Comment by littlepriceonu** [comment]
I've had this issue too, not really sure what happened but I think I clicked on it and pressed Interact button at the same time and it locked up.

**Comment by miicck** [comment]
Hi all, thanks for the reports. I've not been able to reproduce this - any more specifics would be very helpful :)

**Comment by miicck** [comment]
Relevant thread: https://steamcommunity.com/app/1442360/discussions/0/3757726983068896442/

**Comment by swiftimundo** [comment]
Sorry I haven't been able to test. I went away and then got covid. I will try to reproduce this coming week. I've noticed I can save with /save command and not lose progress. Are there any logs/dumps I can send that will be helpful?

**Comment by miicck** [comment]
I think this was fixed by https://github.com/miicck/dont-get-lost/pull/54, but I'm going to leave the issue open for a bit in case people want to report that they are still having the issue.

**Comment by miicck** [comment]
It's been long enough that I'm closing this issue as fixed - please comment if you're still experiencing this issue :)
