### ISSUE TITLE
UI scaling/More readable text

### ISSUE THREAD

**Issue by k4gi** [miicck/dont-get-lost#25]
um so i actually haven't played this game, i just booted it up and started a new game and found that the UI and HUD text is uncomfortably small, if there was a setting to increase the font size, maybe scale up the UI as a whole, that would be great

**Comment by miicck** [comment]
I've added "More readable text" to the title of this, as it's a closely related issue.

**Comment by miicck** [comment]
UI scaling progress: 6a236bb74eaa7712e3e19f1c4c8d36357636a9f1

**Comment by miicck** [comment]
Fixed by: 2e4cbf70686f2ba591c5bbc4cb1b4c9c13fb8b3b
And a bunch of other commits for each of the menus.
