### ISSUE TITLE
Potatoes are not food

### ISSUE THREAD

**Issue by miicck** [miicck/dont-get-lost#27]
Potatoes have lost their food designation (if they ever had one).

**Comment by TacoShower** [comment]
Looks like Assets/resources/items/potato.prefab is just missing a food script assigned to it, I can make a pull reqeust to fix it but it may just be easier for you to do it on your version anyways so you can assign proper values for it

**Comment by Coffee4cr** [comment]
Make it go through baked potato in the furnace.
Raw potatoes kind of suck, raw cabbage is fine

**Comment by Coffee4cr** [comment]
since we have cheese you could also do  a loaded baked potato

**Comment by miicck** [comment]
Thanks for suggestions, I've added a baked potato: fc054733d9320de8fffda54c6aadb8f24fe6fcd0
I think this closes the current issue, but various forms of loaded baked potato may well appear in the future (feel free to add them yourselves if you like! The referenced commit should serve as a guide for how to add items/sprites/recipes).
