### ISSUE TITLE
Hair as colonist items

### ISSUE THREAD

**Issue by porcuspine** [miicck/dont-get-lost#29]
It just feels weird to me to have hair as an item, especially when you're equipping colonists with helmets and then you gain possession of their hair. Maybe some form of customization using a different system than their inventory?

**Comment by miicck** [comment]
Hi, thanks for the report. A different system for types of hair would require more work than it is worth in my opinion. The hair being an item is also a lot less likely to exhibit bugs than a new system would be. Therefore, I'm closing this as a won't fix.
