### ISSUE TITLE
[Multiplayer] tool duplicating

### ISSUE THREAD

**Issue by kisokos03** [miicck/dont-get-lost#35]
When a tool is equipped, another player is able to "take" it by clicking the tool visible in the other's hand. This creates a new tool in the "thief's" inventory, without removing it from the original owner's

**Comment by miicck** [comment]
Thanks for the report! Fixed here: 03719f0a157452b53d66ecf2dabdee64d7504e71 (my favourite kind of fix - one that involves only removing code!).
