### ISSUE TITLE
Cant build near spawn? no problem!

### ISSUE THREAD

**Issue by twoface1556** [miicck/dont-get-lost#6]
Place the "blueprint" of the object while standing out side of the spawn zone and just move it into place where you like to have it. But be careful you wont get it back if you miss place it.

heres  steam link
https://steamcommunity.com/sharedfiles/filedetails/?id=2929030742

**Comment by miicck** [comment]
Thanks for the report!
Fixed by: 2920b15374ab39025c2b12c316c336b55727fe64
