### ISSUE TITLE
Explain cabbage planter setup better in the tutorial

### ISSUE THREAD

**Issue by miicck** [miicck/dont-get-lost#7]
Add more explicit directions in the tutorial.

**Comment by Zerahn** [comment]
It's not just that the directions aren't clear, it's that there are issues with the steps being registered properly. I had a cabbage planter set up to empty into a pantry, the step was flagged complete, and i went to place a guard post. by the time the guard post was placed, without any other change made anywhere in the village, the cabbage planter was no longer registering. i had to pick it up and place it again.

**Comment by miicck** [comment]
Fixed: 6659a966b8311bb113d2e8f3e0876f09ee051ece
