### ISSUE TITLE
Discord needs a moderator

### ISSUE THREAD

**Issue by engineer-pearl** [miicck/dont-get-lost#92]
Sorry to make this an issue, but we haven't heard from you on the discord in a while

People are posting spam, and we really need someone to be named a moderator so that inappropriate material can get cleaned up.

**Comment by miicck** [comment]
Hi, thanks for the post - discord stopped sending me push notifications for some reason. Would you be happy to be named a moderator?

**Comment by engineer-pearl** [comment]
Discord now has moderators. Closing.
